/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as KontoRouteImport } from './routes/konto'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OpretRouteImport } from './routes/opret'
import { Route as TurneringRouteImport } from './routes/turnering'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBoardSessionRouteImport } from './routes/api/board/session'
import { Route as ApiBoardStateRouteImport } from './routes/api/board/state'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const KontoRoute = KontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OpretRoute = OpretRouteImport.update({
  id: '/opret',
  path: '/opret',
  getParentRoute: () => rootRouteImport,
} as any)
const TurneringRoute = TurneringRouteImport.update({
  id: '/turnering',
  path: '/turnering',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBoardSessionRoute = ApiBoardSessionRouteImport.update({
  id: '/api/board/session',
  path: '/api/board/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBoardStateRoute = ApiBoardStateRouteImport.update({
  id: '/api/board/state',
  path: '/api/board/state',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/konto': typeof KontoRoute
  '/login': typeof LoginRoute
  '/opret': typeof OpretRoute
  '/turnering': typeof TurneringRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/board/session': typeof ApiBoardSessionRoute
  '/api/board/state': typeof ApiBoardStateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/konto': typeof KontoRoute
  '/login': typeof LoginRoute
  '/opret': typeof OpretRoute
  '/turnering': typeof TurneringRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/board/session': typeof ApiBoardSessionRoute
  '/api/board/state': typeof ApiBoardStateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/konto': typeof KontoRoute
  '/login': typeof LoginRoute
  '/opret': typeof OpretRoute
  '/turnering': typeof TurneringRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/board/session': typeof ApiBoardSessionRoute
  '/api/board/state': typeof ApiBoardStateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/konto'
    | '/login'
    | '/opret'
    | '/turnering'
    | '/api/auth/$'
    | '/api/board/session'
    | '/api/board/state'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/konto'
    | '/login'
    | '/opret'
    | '/turnering'
    | '/api/auth/$'
    | '/api/board/session'
    | '/api/board/state'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/konto'
    | '/login'
    | '/opret'
    | '/turnering'
    | '/api/auth/$'
    | '/api/board/session'
    | '/api/board/state'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  KontoRoute: typeof KontoRoute
  LoginRoute: typeof LoginRoute
  OpretRoute: typeof OpretRoute
  TurneringRoute: typeof TurneringRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBoardSessionRoute: typeof ApiBoardSessionRoute
  ApiBoardStateRoute: typeof ApiBoardStateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konto': {
      id: '/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof KontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opret': {
      id: '/opret'
      path: '/opret'
      fullPath: '/opret'
      preLoaderRoute: typeof OpretRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turnering': {
      id: '/turnering'
      path: '/turnering'
      fullPath: '/turnering'
      preLoaderRoute: typeof TurneringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/board/session': {
      id: '/api/board/session'
      path: '/api/board/session'
      fullPath: '/api/board/session'
      preLoaderRoute: typeof ApiBoardSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/board/state': {
      id: '/api/board/state'
      path: '/api/board/state'
      fullPath: '/api/board/state'
      preLoaderRoute: typeof ApiBoardStateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  KontoRoute: KontoRoute,
  LoginRoute: LoginRoute,
  OpretRoute: OpretRoute,
  TurneringRoute: TurneringRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBoardSessionRoute: ApiBoardSessionRoute,
  ApiBoardStateRoute: ApiBoardStateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
